### PR TITLE
add smp_affinity script for ipq807x devices

### PR DESCRIPTION
**Pull request by kirdesde**
tested on Dynalink DL-WRX36

Signed-off-by: Dirk Buchwalder <buchwalder@posteo.de>

### CODE REVIEW

**Comment by robimarko** [comment]
This sets ath11k affinity, not the wired driver as far as I can see.

**Comment by kirdesde** [comment]
All right then. You mean something like that?

https://github.com/openwrt/openwrt/blob/ec6293febc244d187e71a6e54f44920be679cde4/target/linux/ramips/mt7621/base-files/etc/uci-defaults/01_enable_packet_steering

**Comment by robimarko** [comment]
Something like this:
https://github.com/openwrt/openwrt/commit/fcbd39689ebfef20c62fe3882d51f3af765e8028

Just the IRQ-s are obviously different

**Comment by XiaoliChan** [comment]
I think this is what you want [portal](https://github.com/1715173329/imoutowrt/commit/5b39e9702c59622e7e2050afee10fb365e622a6c)

**Comment by robimarko** [comment]
Thanks, as you have seen we are gathering some test results on the forum.

**Pull request closed without merging**
