### PR TITLE
ath11k: backport RX decap offload

### PR DESCRIPTION
**Pull request by castiel652**
Backport RX decapsulation offload from 5.16.
This improves RX throughout.

Can be enabled by adding frame_mode=2 to /etc/modules.d/ath11k

Signed-off-by: Zhijun You <hujy652@gmail.com>

### CODE REVIEW

**Comment by robimarko** [comment]
Hi, first of all,
thanks for backporting this.

As you can tell, there is some discussion in the forum on whether this helps/works or whatever.
Can you maybe share some statistics on how you validated if it works?

**Comment by dchard** [comment]
I did try to test this as much as I can (LAN-WLAN and WAN-WLAN), but I see no visible drop in kernel I/O load in any of the test cases.

Question is if it really works or not? Besides checking the ath11k "frame_mode" parameter, is there any other way to see if a connection is offloaded?

The recommended affinity modifications (by @castiel652 ) does help to spread the load to multiple cores:

```
#assign 4 rx interrupts to each cores
echo 8 > /proc/irq/50/smp_affinity
echo 4 > /proc/irq/51/smp_affinity
echo 2 > /proc/irq/52/smp_affinity
echo 1 > /proc/irq/53/smp_affinity

#assign 3 tcl completions to 3 CPUs
echo 4 > /proc/irq/73/smp_affinity
echo 2 > /proc/irq/74/smp_affinity
echo 1 > /proc/irq/75/smp_affinity
```

It might worth to add this by default to the router boot process.

**Comment by castiel652** [comment]
> As you can tell, there is some discussion in the forum on whether this helps/works or whatever. Can you maybe share some statistics on how you validated if it works?

Sorry I don't have any statistics proof right now.
It should just work tho.

**Comment by castiel652** [comment]
> I did try to test this as much as I can (LAN-WLAN and WAN-WLAN), but I see no visible drop in kernel I/O load in any of the test cases.
> 
> Question is if it really works or not? Besides checking the ath11k "frame_mode" parameter, is there any other way to see if a connection is offloaded?

Not really sure. When I was testing encap offload for ath10k on R7800 I can simply tell the difference just by doing iPerf test with one 2x2 device as it will max out both CPUs.
It probably won't be that easy here since IPQ807X is much faster.

**Pull request closed without merging**
