### PR TITLE
ath11k: fix WDS

### PR DESCRIPTION
**Pull request by dspalu32**
Three upstream backports to fix WDS/4addr on ath11k:

1. ath11k: fix ZERO address in probe request: https://patchwork.kernel.org/project/linux-wireless/patch/20201012101733.24137-1-cjhuang@codeaurora.org/
   (Fix inability to connect to APs with hidden SSIDs)
2. ath11k-fix-4addr-tx-failure-AP-STA-modes.patch: https://patchwork.kernel.org/project/linux-wireless/patch/20210720213147.90042-1-jouni@codeaurora.org/
   (Fix borked traffic flow)
3. ath11k-send-multicast-in-4addr.patch: https://patchwork.kernel.org/project/linux-wireless/patch/20210720213147.90042-2-jouni@codeaurora.org/
   (Fix ARP)

### CODE REVIEW

**Comment by castiel652** [comment]
IMO it's probably better to wait for 2 and 3 to be accepted upstream because we don't know if they will change it.
Besides that this PR has formal issue.
Commit title needs to be changed to something like this: **ath11k: fix WDS**

**Comment by castiel652** [comment]
You changed the PR title but didn't change the commit title.

**Comment by dspalu32** [comment]
Ah, sorry, you're right. This is new to me. I didn't edit the default commit title before completing, and apparently can't edit it online once pushed. I can try a force-push from the command line, but won't be at a computer for days. If it can't be modified when received by robimarko, I will delete the PR and retry later next week.

**Comment by robimarko** [comment]
Thanks for the effort, but I see multiple issues.
First, I am not really keen on merging them until they are merged upstream.
Second, this has formal issues, the commit message is good but needs to be expanded so it's clear what WDS issues,
it also lacks SoB signature.
And third, the patches are not exported correctly, they need to be exported using git format patch so that all of the details are preserved.

**Comment by dspalu32** [comment]
This PR is no longer needed. The WDS patches were incorporated into https://github.com/robimarko/openwrt/commit/8dca0044b81d0d181663400f3e839743994f80c5

**Pull request closed without merging**
