### PR TITLE
WAC510

### PR DESCRIPTION
**Pull request by 7604timo**
Hi Robert,

Do you think my hotplug additions for fixing the MAC address is OK?

It seems to be working OK for me on my unit. I will put the access point into production tomorrow at work and configure it with my SSIDs and VLANs to see how it does for a few days.

Tim

### CODE REVIEW

**Comment by robimarko** [comment]
Can you squash your commits?
This does not like a proper way to fix MACs.
Can you check if maybe MACs are available in U-boot environment?

**Comment by 7604timo** [comment]
Only eth0 is available in uboot.

How would that help though?

I can try to squash my commits tomorrow morning - I know I was getting
carried away with them!

Tim

**Comment by robimarko** [comment]
Why not reuse https://github.com/robimarko/openwrt/blob/WAC510/target/linux/ipq806x/base-files/etc/hotplug.d/ieee80211/10_fix_wifi_mac

Its used for exactly the purpose of MAC setting

**Comment by 7604timo** [comment]
Thank you, that looks like a better option indeed!

I'll try it out in the morning.

Tim

**Comment by 7604timo** [comment]
I *think* I've cleaned up the pull-request now, have I?

I've removed the whole script I wrote to change the wifi mac address and added instead a few lines to your script.

Does it all look OK now?

Tim

**Comment by robimarko** [comment]
Your branch is not current.
You gotta rebase it on mine,I rebased mine on master since there were a lot of important changes

**Comment by 7604timo** [comment]
I don't know what I'm doing here with git. All the instructions I can find on rebaseing don't seem to get rid of the 'this branch is xx commits ahead' of yours.

Am I safe to just delete my fork and redo my changes and start again?

Tim

**Comment by robimarko** [comment]
You can do stuff like that pretty easily using GitKraken,much easier than cli git commands for rebase which are terrible

**Comment by 7604timo** [comment]
I've tried rebasing with gitkraken several different ways, all succeeding apparently, but I'm still 45 commits ahead of you somehow.

Given that I've only modified 3 files and I can re-do the changes, I think it's going to be easier to remove my fork and redo it.

Tim

**Comment by robimarko** [comment]
Did you push your changes?

**Comment by 7604timo** [comment]
Yes, I pushed after each rebase..

Tim

**Comment by robimarko** [comment]
Well,then something is really messed up.
You can simply clone my branch,and then cherrypick commits

**Comment by 7604timo** [comment]
I'm going to start again, just using gitkraken as I expect I've messed something up using the git cli.

Tim

**Pull request closed without merging**
