### PR TITLE
ath11k-firmware: update to 2.5.0.1

### PR DESCRIPTION
**Pull request by castiel652**
Update firmware for QCN9074/IPQ8074/IPQ6018
this fixes encap offload

Signed-off-by: Zhijun You <hujy652@gmail.com>

### CODE REVIEW

**Comment by emptyteeth** [comment]
The `PKG_MIRROR_HASH` is incorrect, you can run this to get the correct one

```shell
make package/firmware/ath11k-firmware/check FIXUP=1
```

**Comment by castiel652** [comment]
Oh I thought I already fixed it using that exact command

**Comment by emptyteeth** [comment]
> Oh I thought I already fixed it using that exact command
> EDIT: just ran it again and it's the same HASH

Don't know why I got this one

```shell
> sha256sum dl/ath11k-firmware-2021-07-20-d4003c19.tar.xz 
6839081bafbc56d3b8e41d30790b20813c349cbc1732e887347ef5ed3ea717e4  dl/ath11k-firmware-2021-07-20-d4003c19.tar.xz
```

**Comment by robimarko** [comment]
Is the hash now correct?
I am on vacation and the internet is really bad so I cant check, otherwise, I would have already merged this.
Especially since it finally introduces significant improvements and a changelog for the first time.

**Comment by rabbidrabbit** [comment]
I get the same hash as @emptyteeth 
jonathan@debian:~/git/openwrt/dl$ sha256sum ath11k-firmware-2021-07-20-d4003c19.tar.xz
6839081bafbc56d3b8e41d30790b20813c349cbc1732e887347ef5ed3ea717e4  ath11k-firmware-2021-07-20-d4003c19.tar.xz

**Comment by robimarko** [comment]
Ok, then I will merge this.
Thanks

**Pull request merged**
