### PR TITLE
[WIP]Add support for Netgear SXR80

### PR DESCRIPTION
**Pull request by Flole998**
Adds support for the IPQ8074A-based Netgear Orbi Pro WiFi 6 (SXR80)

Signed-off-by: Flole <flole@flole.de>

### CODE REVIEW

**Comment by robimarko** [comment]
I went over this yesterday, I am gonna be honest and say that there are issues.
From alphabetical ordering, image recipe which is copy/paste from AX3600 including the FIT config name which is for sure incorrect and will fail to boot if permanently flashed to weird indentations etc.

**Comment by Flole998** [comment]
Sorry I haven't found time to look into this until now. I don't know what exactly you mean with "FIT config name", is that somewhere in generic.mk? I will fix the alphabetical ordering aswell as the intendations now.

**Comment by robimarko** [comment]
Its:
`DEVICE_DTS_CONFIG := config@ac04`

This needs to match what the bootloader expects to read, and its for sure not ac04 on hk01 board.
You can get this from the stock FW once the bootloader loads the FIT image.

**Comment by huangya90** [comment]
@Flole998 so you are trying to figure out how to flash the firmware for SXR80 right?

**Comment by Flole998** [comment]
@huangya90 Not really, the startcmd in U-Boot needs changing and I am not yet sure to what I should change it, so I don't know yet how to flash the firmware then (which "format" to use).

**Comment by Flole998** [comment]
Finally the changes for mmc-updates from https://github.com/openwrt/openwrt/pull/3469 are merged. Once the changes are in this repo the only thing really left is using those for sysupgrade, fixing the image recipe aswell as documenting how to change u-boots cmdline.

**Comment by Flole998** [comment]
This PR has been replaced by #22

**Pull request closed without merging**
