### PR TITLE
ipq807x: Add support for Netgear WAX218

### PR DESCRIPTION
**Pull request by mrnuke**
ipq807x: add support for Netgear WAX218
================================

Netgear WAX218 is a 802.11ax AP claiming AX3600 support. It is wall
or ceiling mountable. It can be powered via PoE, or a 12 V adapter.

The board has footprints for 2.54mm UART headers. They're difficult to
solder because the GND is connected to a large copper plane. Only try
soldering if you are very skilled. Otherwise, use pogo pins.

Specifications:
---------------
    * CPU: Qualcomm IPQ8072A Quad core Cortex-A53 2.2GHz
    * RAM: 366 MB of RAM available to OS, not sure of total amount
    * Storage: Macronix MX30UF2G18AC 256MB NAND
    * Ethernet:
            * 2.5G RJ45 port (QCA8081) with PoE input
    * WLAN:
            * 2.4GHz/5GHz with 8 antennas
    * LEDs:
            * Power (Amber)
            * LAN (Blue)
            * 2G WLAN (Blue)
            * 5G WLAN (Blue)
    * Buttons:
            * 1x Factory reset
    * Power: 12V DC Jack
    * UART: Two 4-pin unpopulated headers near the LEDs
            * "J2 UART" is the CPU UART, 3.3 V level

Not (yet) implemented:
======================
  * WiFi (Needs board-specific firmware files)

Installation:
=============

Web UI method
-------------

Flashing OpenWRT using the vendor's Web UI is problematic on this
device. The u-boot mechanism for communicating the active rootfs is
antiquated and unreliable. Instead of setting the kernel commandline,
it relies on patching the DTS partitions of the nand node. The way
partitions are patched is incompatible with newer kernels.

Newer kernels use the SMEM partition table, which puts "rootfs" on
mtd12. The vendor's Web UI will flash to either mtd12 or mtd14. One
reliable way to boot from mtd14 and avoid boot loops is to use an
initramfs image.

 1. In the factory web UI, navigate to System Manager -> Firmware.
 2. In the "Local Firmware Upgrade" section, click Browse
 3. Navigate and select the 'web-ui-factory.fit' image
 4. Click "Upload"
 5. On the following page, click on "Proceed"

The flash proceeds at this point and the system will reboot
automatically to OpenWRT.

 6. Flash the 'nand-sysupgrade.bin' using Luci or the commandline

SSH method
----------

Enable SSH using the CLI or Web UI. The root account is locked out to
ssh, and the admin account defaults to Netgear's CLI application.
So we need to get creative:

First, make sure the device boots from the second firmware partition:

    ssh -okexalgorithms=diffie-hellman-group14-sha1 admin@<ipaddr> \
        /usr/sbin/fw_setenv active_fw 1

Then reboot the device, and run the update:

    scp -O -o kexalgorithms=diffie-hellman-group14-sha1 \
        -o hostkeyalgorithms=ssh-rsa \
        netgear_wax218-squashfs-nand-factory.ubi \
        admin@<ipaddr>:/tmp/openwrt.ubi

    ssh -okexalgorithms=diffie-hellman-group14-sha1 admin@<ipaddr> \
        /usr/sbin/ubiformat /dev/mtd12 -f /tmp/openwrt.ubi

    ssh -okexalgorithms=diffie-hellman-group14-sha1 admin@<ipaddr> \
        /usr/sbin/fw_setenv active_fw 0

Now reboot the device, and it should boot into a ready-to-use OpenWRT.

Funny message before I realized I could unlock FW via serial console
====================================================

The WAX218 claims to be an AX3600 access point. I couldn't really test that, because the vendor firmware asked me to accept to the vendor's SCREW-U-LA. Having accidentally glanced of this SCREW-U-LA, I realized thatI didn't want to sign away rights to my unborn babies. I didn't accept the SCREW-U-LA, thus did not test the firmware.

### CODE REVIEW

**Comment by robimarko** [comment]
No point in backporting the upstream QCA807x PHY driver at all, all it will do is conflict with the SSDK one as they are messing with the PHY from various parts of SSDK via the PHY driver

**Comment by mrnuke** [comment]
I agree on the QCA807x PHY driver point.

I have a problem with the firmware files. I see existing ipq-wifi files have some ID strings in the header:

```
$ strings package/firmware/ipq-wifi/board-qnap_301w.ipq8074 |head -n 4
QCA-ATH11K-BOARD
bus=ahb,qmi-chip-id=0,qmi-board-id=255,variant=QNAP-301w
LPTX\`dh
```

However, the firmware files I extracted from the vendor firmware do not:

```
$ strings lib-firmware/IPQ8074/bdwlan.b290 |head -n4
LPTX\`dh


?############
```

And I don't know how to get ath11k  to load these files. Any suggestions?

**Comment by kirdesde** [comment]
> 

You can add the ID string via ath11k-bdencoder (https://github.com/ecsv/qca-swiss-army-knife)

But first you need to figure out, that board id your device is using, have a look in the stock bootlog (board_id etc.)

Create a json file like that for example:

`[
    {
        "names": [
            "bus=ahb,qmi-chip-id=0,qmi-board-id=255,variant=Netgear-RAX120v2"
        ],
        "data": "bus=ahb,qmi-chip-id=0,qmi-board-id=255,variant=Netgear-RAX120v2.bin"
    }`
    
    Rename the board file accordingly (bus=ahb,qmi-chip-id=0,qmi-board-id=255,variant=Netgear-RAX120v2.bin).
    
    Last step is to add a DTS property like that (ID in hexadecimal)
    
    `&wifi {
	status = "okay";

	qcom,board_id = <0xff>; 
	qcom,ath11k-calibration-variant = "Netgear-RAX120v2";
};`

**Comment by mrnuke** [comment]
> You can add the ID string via ath11k-bdencoder (https://github.com/ecsv/qca-swiss-army-knife)

That's awesome! Thank you!

**Comment by mrnuke** [comment]
I ran into a snag with UBI. If I flash the `-nand-sysupgrade.ubi` image, the flash will complete without issue. However, this puts the machine in a bootloop:

```
Starting kernel ...
Jumping to AARCH64 kernel via monitor
...
[    0.000000] Kernel command line: console=ttyMSM0 ubi.mtd=rootfs root=mtd:ubi_rootfs rootfstype=squashfs rootwait
...
[    1.047053] 0x000001000000-0x000007f00000 : "rootfs"
[    1.134149] mtd: device 12 (rootfs) set to be root filesystem
[    1.134434] mtdsplit: no squashfs found in "rootfs"
[    1.138906] 0x000007f00000-0x000008800000 : "0:wififw"
[    1.150650] 0x000008800000-0x00000f700000 : "rootfs_1"
[    1.233793] 0x00000f700000-0x000010000000 : "0:wififw_1"
...
[    1.808420] mtd:ubi_rootfs: Can't open blockdev
[    1.808440] VFS: Cannot open root device "mtd:ubi_rootfs" or unknown-block(31,12): error -2
...
[    1.931009] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(31,12)
```

### My observations:

- The vendor Web UI flashed the image to mtd14
- There was no way to select the destination partition (mtd14 or mtd12)

How would I go on about this?

**Comment by kirdesde** [comment]
> I ran into a snag with UBI. If I flash the `-nand-sysupgrade.ubi` image, the flash will complete without issue. However, this puts the machine in a bootloop:
> 
> ```
> Starting kernel ...
> Jumping to AARCH64 kernel via monitor
> ...
> [    0.000000] Kernel command line: console=ttyMSM0 ubi.mtd=rootfs root=mtd:ubi_rootfs rootfstype=squashfs rootwait
> ...
> [    1.047053] 0x000001000000-0x000007f00000 : "rootfs"
> [    1.134149] mtd: device 12 (rootfs) set to be root filesystem
> [    1.134434] mtdsplit: no squashfs found in "rootfs"
> [    1.138906] 0x000007f00000-0x000008800000 : "0:wififw"
> [    1.150650] 0x000008800000-0x00000f700000 : "rootfs_1"
> [    1.233793] 0x00000f700000-0x000010000000 : "0:wififw_1"
> ...
> [    1.808420] mtd:ubi_rootfs: Can't open blockdev
> [    1.808440] VFS: Cannot open root device "mtd:ubi_rootfs" or unknown-block(31,12): error -2
> ...
> [    1.931009] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(31,12)
> ```
> 
> Full log here:
> 
>     * https://gist.github.com/mrnuke/f0c31dd4b66bb4cf07e4810dd02f9816
> 
> 
> ### My observations:
> 
>     * The vendor Web UI flashed the image to mtd14
> 
>     * There was no way to select the destination partition (mtd14 or mtd12)
> 
> 
> How would I go on about this?

Are you sure you flashed a -nand-sysupgrade.ubi image? This is not part of your image definition...
Or was it the factory.ubi?

However, I would not rely on the stock firmware upgrade functionality and flash the image from an openwrt initramfs via ubiformat.

ubiformat /dev/mtdx -y -f factory.ubi.

Ubiformat creates then the ubi-device with the ubi volumes according to the openwrt definition.

**Comment by mrnuke** [comment]
You are correct. I did mean to type `-squashfs-nand-factory.ubi`.

It appears to me that the vendor firmware uses ubiformat and other openwrt niceties:

```
[  520.259970] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" stops
Performing system upgrade...
senao dual image upgrade, upgrade the alternative partion: rootfs_1
ubiformat: mtd14 (nand), size 116391936 bytes (111.0 MiB), 888 eraseblocks of 131072 bytes (128.0 KiB), min. I/O size 2048 bytes
libscan: scanning eraseblock 887 -- 100 % complete
```
The issue is, we are booting from mtd14, but looking at mtd12 for the rootfs. How do we convince linux to look at mtd14 for the rootfs?

**Comment by kirdesde** [comment]
> You are correct. I did mean to type `-squashfs-nand-factory.ubi`.
> 
> It appears to me that the vendor firmware uses ubiformat and other openwrt niceties:
> 
> ```
> [  520.259970] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" stops
> Performing system upgrade...
> senao dual image upgrade, upgrade the alternative partion: rootfs_1
> ubiformat: mtd14 (nand), size 116391936 bytes (111.0 MiB), 888 eraseblocks of 131072 bytes (128.0 KiB), min. I/O size 2048 bytes
> libscan: scanning eraseblock 887 -- 100 % complete
> ```
> 
> The issue is, we are booting from mtd14, but looking at mtd12 for the rootfs. How do we convince linux to look at mtd14 for the rootfs?

set bootargs to: ....ubi.mtd=rootfs_1 (actually that should be part of the partition switch logic, but maybe netgear doesn't implemented this in u-boot and uses a different rootfs detection)

**Comment by robimarko** [comment]
U-boot will patch the DTB, it looks for the NAND controller compatible and then patches the partitions but using the legacy bindings.
Using SMEM parser will give you the same but in a modern fashion.

**Comment by robimarko** [comment]
https://git.codelinaro.org/clo/qsdk/oss/boot/u-boot-2016/-/blob/NHSS.QSDK.12.0/board/qca/arm/common/fdt_fixup.c#L967

Its looking for the NAND controller compatible and will just dump the partitions under it, if you use DTC on a running board and dump the DTS, you will see that it adds the partitions but they are using the legacy bindings and thankfully these are ignored by the kernel.

Due to this crap of a bootloader if you want to use fixed partitions, a dummy partitions subnode under the controller but not under the NAND flash node you add a disabled node like its done for AX9000.

**Comment by mrnuke** [comment]
Thank you for the references!

> Just use SMEM parser, it will give you the same nodes as bootloader parses SMEM partition table and patches that in

I have `compatible = "qcom,smem-part";` right now. The issue I have is this doesn't work if OpenWRT is flashed to mtd14("rootfs_1"): https://github.com/robimarko/openwrt/issues/47#issuecomment-1174463961_

**Comment by robimarko** [comment]
Hm, I assume that they are using bootconfig as the source of which rootfs to use and update that via SCM.
Thats the only way if bootqca/bootipq is used as bootcmd unless they modified the bootloader which wouldn't be a new thing for Netgear

**Comment by mrnuke** [comment]
In order to get things booting properly, I need to do:

    bootargs-append = " ubi.block=0,rootfs root=/dev/ubiblock0_1";

I wonder if there's a way to specify ubi.block and root using the ubi and volume names instead of numerical constants.

**Comment by mrnuke** [comment]
Turns out we really can't rely on the vendor u-boot patching things. T

```
&qpic_nand {
	compatible = "qcom,ebi2-nandc-bam-v1.5.0", "qcom,ipq8074-nand";
	status = "okay";

	nand@0 {
		reg = <0>;
		nand-ecc-strength = <4>;
		nand-ecc-step-size = <512>;
		nand-bus-width = <8>;
	};
};
```
Results in: 
```
[    0.674087] nand: device found, Manufacturer ID: 0xc2, Chip ID: 0xaa
[    0.675733] nand: Macronix MX30UF2G18AC
[    0.682350] nand: 256 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    0.685901] Block protection check failed
[    0.693782] qcom_nand.0: error parsing ofpart partition /soc/nand@79b0000/nand@0/partition@0 (/soc/nand@79b0000/nand@0)
```

**Comment by robimarko** [comment]
I think that in theory using names for volumes should work, however, I have never been able to actually get that working.

BTW, whats the purpose of `qcom,ebi2-nandc-bam-v1.5.0`?

**Comment by mrnuke** [comment]
> BTW, whats the purpose of `qcom,ebi2-nandc-bam-v1.5.0`?

Making sure u-boot patches that DTS with partition information... That worked great!
Using `append-ubi | qsdk-ipq-factory-nand` is  not going to work.

### What's next

My next idea is to ubinize the initramfs image, and place that in a `qsdk-ipq-factory-nand` container. I couldn;t quite figure out how to do that.

**Comment by robimarko** [comment]
Closing for now as target is in OpenWrt PR stage so all new devices will go directly to OpenWrt after target is merged.

**Comment by jmspswny** [comment]
@mrnuke - are you still working on this / issuing a PR to the main openwrt repo?

**Comment by mrnuke** [comment]
@jmspswny I need to rebase my work and re-test it, yes.

**Comment by jmspswny** [comment]
@mrnuke  - awesome.  I'll leave it alone then.  I'm happy to help with testing if you'd like

**Comment by mrnuke** [comment]
@jmspswny, you may go ahead and give https://github.com/mrnuke/openwrt/tree/wax218-devel a try. It's got an annoying behavior where QCA-SSDK spams the kernel log with:

```hsl_phy_phydev_get[773]:ERROR:phy_addr 0 phydev is NULL```

but otherwise did not brick the box.

**Comment by mrnuke** [comment]
Upstream pull request here: https://github.com/openwrt/openwrt/pull/11959

**Pull request closed without merging**
